version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        hostname: postgres
        environment: 
            POSTGRES_USER: flask
            POSTGRES_PASSWORD: flask123
            POSTGRES_DB: flask_db
        ports:
            - "5432:5432"
        networks:
            - my_network
        container_name: db

    web:
        restart: always
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        ports:
            - "5000-5000"
        depends_on:
            - db
        networks:
            - my_network
        image: flask-app
        container_name: web

    server:
        restart: always
        build: ./server
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        networks:
            - my_network
        image: flask-server
        container_name: server

networks:
    my_network:


