version: "1"
services:
    db:
        image: postgres:latest
        restart: always
        hostname: postgres
        environment: 
            POSTGRES_USER: flask
            POSTGRES_PASSWORD: flask123
            POSTGRES_DB: flask_db
        ports:
            - "5432:5432"
        networks:
            - my_network

    web:
        restart: always
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        ports:
            - "5000-5000"
        depends_on:
            - db
        networks:
            - my_network

    server:
        restart: always
        build: ./server
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        networks:
            - my_network

networks:
    my_network:


