version: "1"
services:
    flask_app:
        build:
            context: ./flask_app
        ports:
            - "5000:5000"
        depends_on:
            - db
        networks:
            - my_network

    db:
        image: postgres:latest
        environment: 
            POSTGRES_USER: flask
            POSTGRES_PASSWORD: flask123
            POSTGRES_DB: flask_db
        ports:
            - "5432:5432"
        networks:
            - my_network

networks:
    my_network:


